// components/site/MarqueeStrip.tsx
import Link from "next/link";
import { formatDate } from "@/lib/format";
import { defaultSiteLocale, type SiteLocale, withLocalePath } from "@/lib/i18n";
import type { HomeActivity } from "@/types/site";

export function MarqueeStrip({ items, locale = defaultSiteLocale }: { items: HomeActivity[]; locale?: SiteLocale }) {
  const loopItems = [...items, ...items];

  return (
    <section className="marquee-section">
      <div className="marquee-track">
        {loopItems.map((item, index) => (
          <Link key={`${item.id}-${index}`} className="marquee-card" href={withLocalePath(locale, item.href)}>
            <span className="marquee-card__date">{formatDate(item.date, locale)}</span>
            <b>{item.label}</b>
            <strong>{item.title}</strong>
            <p>{item.summary}</p>
          </Link>
        ))}
      </div>
    </section>
  );
}

// src/components/site/MarqueeStrip.vue
<template>
  <section class="marquee-section">
    <div class="marquee-track">
      <AppLink
        v-for="(item, index) in loopItems"
        :key="`${item.id}-${index}`"
        class-name="marquee-card"
        :to="withLocalePath(locale, item.href)"
      >
        <span class="marquee-card__date">{{ formatDate(item.date, locale) }}</span>
        <b>{{ item.label }}</b>
        <strong>{{ item.title }}</strong>
        <p>{{ item.summary }}</p>
      </AppLink>
    </div>
  </section>
</template>

<script setup lang="ts">
import { computed } from "vue";
import AppLink from "@/components/site/AppLink.vue";
import { formatDate } from "@/lib/format";
import { defaultSiteLocale, type SiteLocale, withLocalePath } from "@/lib/i18n";
import type { HomeActivity } from "@/types/site";

const props = withDefaults(
  defineProps<{
    items: HomeActivity[];
    locale?: SiteLocale;
  }>(),
  {
    locale: defaultSiteLocale,
  },
);

const loopItems = computed(() => [...props.items, ...props.items]);
</script>
