// components/site/PageHero.tsx
import Link from "next/link";
import type { PageHero as PageHeroType } from "@/types/site";

export function PageHero({ hero }: { hero: PageHeroType }) {
  const hasSubtitle = Boolean(hero.subtitle?.trim());
  const hasDescription = Boolean(hero.description?.trim());

  return (
    <section className="page-hero">
      <div className="page-hero__content">
        <p className="page-hero__eyebrow">{hero.eyebrow}</p>
        <h1>{hero.title}</h1>
        {hasSubtitle ? <p className="page-hero__subtitle">{hero.subtitle}</p> : null}
        {hasDescription ? <p className="page-hero__description">{hero.description}</p> : null}
        {(hero.primaryAction || hero.secondaryAction) && (
          <div className="page-hero__actions">
            {hero.primaryAction ? (
              <Link className="button-link button-link--primary" href={hero.primaryAction.href}>
                {hero.primaryAction.label}
              </Link>
            ) : null}
            {hero.secondaryAction ? (
              <Link className="button-link button-link--secondary" href={hero.secondaryAction.href}>
                {hero.secondaryAction.label}
              </Link>
            ) : null}
          </div>
        )}
      </div>
    </section>
  );
}

// src/components/site/PageHero.vue
<template>
  <section class="page-hero">
    <div class="page-hero__content">
      <p class="page-hero__eyebrow">{{ hero.eyebrow }}</p>
      <h1>{{ hero.title }}</h1>
      <p v-if="hero.subtitle?.trim()" class="page-hero__subtitle">{{ hero.subtitle }}</p>
      <p v-if="hero.description?.trim()" class="page-hero__description">{{ hero.description }}</p>
      <div v-if="hero.primaryAction || hero.secondaryAction" class="page-hero__actions">
        <AppLink
          v-if="hero.primaryAction"
          class-name="button-link button-link--primary"
          :to="hero.primaryAction.href"
        >
          {{ hero.primaryAction.label }}
        </AppLink>
        <AppLink
          v-if="hero.secondaryAction"
          class-name="button-link button-link--secondary"
          :to="hero.secondaryAction.href"
        >
          {{ hero.secondaryAction.label }}
        </AppLink>
      </div>
    </div>
  </section>
</template>

<script setup lang="ts">
import AppLink from "@/components/site/AppLink.vue";
import type { PageHero as PageHeroType } from "@/types/site";

defineProps<{
  hero: PageHeroType;
}>();
</script>
