// components/site/RecordDirectory.tsx
import Link from "next/link";
import { defaultSiteLocale, getSiteUiText, type SiteLocale } from "@/lib/i18n";
import type { RecordGroup } from "@/types/site";

type RecordDirectoryProps = {
  groups: RecordGroup[];
  locale?: SiteLocale;
};

export function RecordDirectory({ groups, locale = defaultSiteLocale }: RecordDirectoryProps) {
  const visibleGroups = groups
    .map((group) => ({
      ...group,
      items: group.items.filter((item) => item.visible !== false),
    }))
    .filter((group) => group.items.length > 0);
  const ui = getSiteUiText(locale);

  return (
    <div className="record-directory">
      <aside className="record-directory__sidebar">
        <div className="record-directory__sidebar-card">
          <p className="record-directory__eyebrow">{ui.publications.sectionNavigation}</p>
          <nav className="record-directory__nav" aria-label={ui.publications.navAriaLabel}>
            {visibleGroups.map((group) => (
              <a key={group.id} className="record-directory__nav-link" href={`#${group.id}`}>
                <span className="record-directory__nav-main">
                  <span className="record-directory__nav-icon">{group.icon}</span>
                  <span className="record-directory__nav-text">
                    <strong>{group.title}</strong>
                    {group.summary ? <small>{group.summary}</small> : null}
                  </span>
                </span>
                <span className="record-directory__nav-count">{group.items.length}</span>
              </a>
            ))}
          </nav>
        </div>
      </aside>

      <div className="record-directory__content">
        {visibleGroups.map((group) => (
          <section key={group.id} className="record-section" id={group.id}>
            <div className="record-section__header">
              <div className="record-section__title">
                <span className="record-section__icon">{group.icon}</span>
                <div>
                  <p className="record-section__eyebrow">{ui.publications.recordsCount(group.items.length)}</p>
                  <h2>{group.title}</h2>
                  {group.summary ? <p>{group.summary}</p> : null}
                </div>
              </div>
            </div>

            <div className="record-section__list">
              {group.items.map((item) => (
                <article key={item.id} className="record-entry">
                  <p className="record-entry__meta">{item.meta || "-"}</p>
                  <div className="record-entry__body">
                    <h3>{item.title}</h3>
                    {item.subtitle ? <p className="record-entry__subtitle">{item.subtitle}</p> : null}
                    {item.summary ? <p className="record-entry__summary">{item.summary}</p> : null}
                    {item.link ? (
                      <Link className="record-entry__link" href={item.link} target="_blank">
                        {ui.publications.viewSource}
                      </Link>
                    ) : null}
                  </div>
                </article>
              ))}
            </div>
          </section>
        ))}
      </div>
    </div>
  );
}

// src/components/site/RecordDirectory.vue
<template>
  <div class="record-directory">
    <aside class="record-directory__sidebar">
      <div class="record-directory__sidebar-card">
        <p class="record-directory__eyebrow">{{ ui.publications.sectionNavigation }}</p>
        <nav class="record-directory__nav" :aria-label="ui.publications.navAriaLabel">
          <a
            v-for="group in visibleGroups"
            :key="group.id"
            class="record-directory__nav-link"
            :href="`#${group.id}`"
          >
            <span class="record-directory__nav-main">
              <span class="record-directory__nav-icon">{{ group.icon }}</span>
              <span class="record-directory__nav-text">
                <strong>{{ group.title }}</strong>
                <small v-if="group.summary">{{ group.summary }}</small>
              </span>
            </span>
            <span class="record-directory__nav-count">{{ group.items.length }}</span>
          </a>
        </nav>
      </div>
    </aside>

    <div class="record-directory__content">
      <section v-for="group in visibleGroups" :id="group.id" :key="group.id" class="record-section">
        <div class="record-section__header">
          <div class="record-section__title">
            <span class="record-section__icon">{{ group.icon }}</span>
            <div>
              <p class="record-section__eyebrow">{{ ui.publications.recordsCount(group.items.length) }}</p>
              <h2>{{ group.title }}</h2>
              <p v-if="group.summary">{{ group.summary }}</p>
            </div>
          </div>
        </div>

        <div class="record-section__list">
          <article v-for="item in group.items" :key="item.id" class="record-entry">
            <p class="record-entry__meta">{{ item.meta || "-" }}</p>
            <div class="record-entry__body">
              <h3>{{ item.title }}</h3>
              <p v-if="item.subtitle" class="record-entry__subtitle">{{ item.subtitle }}</p>
              <p v-if="item.summary" class="record-entry__summary">{{ item.summary }}</p>
              <AppLink
                v-if="item.link"
                class-name="record-entry__link"
                :target="getExternalTarget(item.link)"
                :to="item.link"
              >
                {{ ui.publications.viewSource }}
              </AppLink>
            </div>
          </article>
        </div>
      </section>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed } from "vue";
import AppLink from "@/components/site/AppLink.vue";
import { defaultSiteLocale, getSiteUiText, type SiteLocale } from "@/lib/i18n";
import type { RecordGroup } from "@/types/site";

const props = withDefaults(
  defineProps<{
    groups: RecordGroup[];
    locale?: SiteLocale;
  }>(),
  {
    locale: defaultSiteLocale,
  },
);

const visibleGroups = computed(() =>
  props.groups
    .map((group) => ({
      ...group,
      items: group.items.filter((item) => item.visible !== false),
    }))
    .filter((group) => group.items.length > 0),
);

const ui = computed(() => getSiteUiText(props.locale));

const getExternalTarget = (href: string) => (/^(https?:)?\/\//.test(href) ? "_blank" : undefined);
</script>
