// components/site/SiteHeader.tsx
import Link from "next/link";
import {
  getShellAdminLabel,
  getShellLabName,
  getShellNavigationLabel,
  localeLabels,
  removeLocalePrefix,
  siteLocales,
  type SiteLocale,
  withLocalePath,
} from "@/lib/i18n";
import type { NavItem } from "@/types/site";

type SiteHeaderProps = {
  labName: string;
  shortName: string;
  navigation: NavItem[];
  adminLabel: string;
  locale: SiteLocale;
  pathname: string;
};

export function SiteHeader({ labName, shortName, navigation, adminLabel, locale, pathname }: SiteHeaderProps) {
  const currentPath = removeLocalePrefix(pathname);
  const brandName = getShellLabName(locale) || labName;
  const adminEntryLabel = getShellAdminLabel(locale) || adminLabel;
  const navLabel = locale === "en" ? "Primary navigation" : locale === "ja" ? "メインナビゲーション" : "主导航";
  const switcherLabel = locale === "en" ? "Language switcher" : locale === "ja" ? "言語切替" : "语言切换";

  return (
    <header className="site-header">
      <div className="site-header__inner">
        <Link className="site-brand" href={withLocalePath(locale, "/")}>
          <span className="site-brand__mark">{shortName}</span>
          <span className="site-brand__text">
            <strong>{brandName}</strong>
            <small>{shortName}</small>
          </span>
        </Link>

        <nav className="site-nav" aria-label={navLabel}>
          {navigation.map((item) => (
            <Link key={item.href} className="site-nav__link" href={withLocalePath(locale, item.href)}>
              {getShellNavigationLabel(locale, item.href, item.label)}
            </Link>
          ))}
        </nav>

        <div className="site-header__controls">
          <div className="language-switcher" aria-label={switcherLabel}>
            {siteLocales.map((targetLocale) => (
              <Link
                key={targetLocale}
                className={`language-switcher__link ${targetLocale === locale ? "is-active" : ""}`}
                href={withLocalePath(targetLocale, currentPath)}
                hrefLang={targetLocale}
                lang={targetLocale}
              >
                {localeLabels[targetLocale]}
              </Link>
            ))}
          </div>

          <Link className="admin-entry" href="/admin/login">
            {adminEntryLabel}
          </Link>
        </div>
      </div>
    </header>
  );
}

// src/components/site/SiteHeader.vue
<template>
  <header class="site-header">
    <div class="site-header__inner">
      <AppLink class-name="site-brand" :to="withLocalePath(locale, '/')">
        <span class="site-brand__mark">{{ shortName }}</span>
        <span class="site-brand__text">
          <strong>{{ brandName }}</strong>
          <small>{{ shortName }}</small>
        </span>
      </AppLink>

      <nav class="site-nav" :aria-label="navLabel">
        <AppLink
          v-for="item in navigation"
          :key="item.href"
          class-name="site-nav__link"
          :to="withLocalePath(locale, item.href)"
        >
          {{ getShellNavigationLabel(locale, item.href, item.label) }}
        </AppLink>
      </nav>

      <div class="site-header__controls">
        <div class="language-switcher" :aria-label="switcherLabel">
          <RouterLink
            v-for="targetLocale in siteLocales"
            :key="targetLocale"
            :class="['language-switcher__link', { 'is-active': targetLocale === locale }]"
            :href-lang="targetLocale"
            :lang="targetLocale"
            :to="withLocalePath(targetLocale, currentPath)"
          >
            {{ localeLabels[targetLocale] }}
          </RouterLink>
        </div>
      </div>
    </div>
  </header>
</template>

<script setup lang="ts">
import { computed } from "vue";
import { useRoute, RouterLink } from "vue-router";
import AppLink from "@/components/site/AppLink.vue";
import {
  getShellLabName,
  getShellNavigationLabel,
  localeLabels,
  removeLocalePrefix,
  siteLocales,
  type SiteLocale,
  withLocalePath,
} from "@/lib/i18n";
import type { NavItem } from "@/types/site";

const props = defineProps<{
  labName: string;
  shortName: string;
  navigation: NavItem[];
  locale: SiteLocale;
}>();

const route = useRoute();
const currentPath = computed(() => removeLocalePrefix(route.fullPath));
const brandName = computed(() => getShellLabName(props.locale) || props.labName);
const navLabel = computed(() =>
  props.locale === "en" ? "Primary navigation" : props.locale === "ja" ? "メインナビゲーション" : "主导航",
);
const switcherLabel = computed(() =>
  props.locale === "en" ? "Language switcher" : props.locale === "ja" ? "言語切替" : "语言切换",
);
</script>
